import type { Quote } from "./_type";

// Batch besar kutipan kerja keras & sukses — supaya kolam kutipan makin banyak
// dan jarang berulang saat di-mix acak. Campuran tokoh dunia, pengusaha,
// peribahasa, semangat kerja, dan semangat khas Dapur MBG.
export const SUKSES: Quote[] = [
  { teks: "Sukses adalah kemampuan melangkah dari satu kegagalan ke kegagalan lain tanpa kehilangan semangat.", sumber: "Winston Churchill", kategori: "Sukses" },
  { teks: "Aku tidak gagal. Aku hanya menemukan sepuluh ribu cara yang tidak berhasil.", sumber: "Thomas Alva Edison", kategori: "Sukses" },
  { teks: "Rahasia untuk maju adalah memulai.", sumber: "Mark Twain", kategori: "Sukses" },
  { teks: "Sukses biasanya datang pada mereka yang terlalu sibuk untuk mencarinya.", sumber: "Henry David Thoreau", kategori: "Sukses" },
  { teks: "Jangan menilai hari dari panen yang kau tuai, tapi dari benih yang kau tanam.", sumber: "Robert Louis Stevenson", kategori: "Sukses" },
  { teks: "Masa depan milik mereka yang percaya pada keindahan mimpi-mimpinya.", sumber: "Eleanor Roosevelt", kategori: "Sukses" },
  { teks: "Percayalah kamu bisa, maka kamu sudah menempuh separuh perjalanan.", sumber: "Theodore Roosevelt", kategori: "Sukses" },
  { teks: "Kesempurnaan tak bisa diraih, tapi dengan mengejarnya kita menggapai keunggulan.", sumber: "Vince Lombardi", kategori: "Sukses" },
  { teks: "Satu-satunya tempat sukses datang sebelum kerja hanyalah di dalam kamus.", sumber: "Vidal Sassoon", kategori: "Sukses" },
  { teks: "Entah kau pikir bisa atau tidak bisa, kau benar.", sumber: "Henry Ford", kategori: "Sukses" },
  { teks: "Kualitas bukan kebetulan; ia selalu hasil dari usaha yang cerdas.", sumber: "John Ruskin", kategori: "Sukses" },
  { teks: "Pekerjaan besar diselesaikan bukan dengan kekuatan, melainkan dengan ketekunan.", sumber: "Samuel Johnson", kategori: "Sukses" },
  { teks: "Kekuatan sejati tidak datang dari fisik, tapi dari kemauan yang gigih.", sumber: "Mahatma Gandhi", kategori: "Sukses" },
  { teks: "Orang yang tak pernah membuat kesalahan tak pernah mencoba hal baru.", sumber: "Albert Einstein", kategori: "Sukses" },
  { teks: "Hidup seperti mengayuh sepeda: agar seimbang, kau harus terus bergerak.", sumber: "Albert Einstein", kategori: "Sukses" },
  { teks: "Tidak ada lift menuju sukses; kau harus menaiki tangganya.", sumber: "Zig Ziglar", kategori: "Sukses" },
  { teks: "Motivasi membuatmu memulai, kebiasaan membuatmu bertahan.", sumber: "Jim Ryun", kategori: "Sukses" },
  { teks: "Kegagalan hanyalah kesempatan untuk memulai lagi dengan lebih cerdas.", sumber: "Henry Ford", kategori: "Sukses" },
  { teks: "Peluang tak akan menghampiri; kaulah yang harus menciptakannya.", sumber: "Chris Grosser", kategori: "Sukses" },
  { teks: "Jangan tunggu kesempatan, ciptakanlah.", sumber: "George Bernard Shaw", kategori: "Sukses" },
  { teks: "Keberhasilan berpihak pada mereka yang berani mencoba.", sumber: "Virgil", kategori: "Sukses" },
  { teks: "Jangan hitung hari; buatlah hari itu berarti.", sumber: "Muhammad Ali", kategori: "Sukses" },
  { teks: "Yang membedakan juara dari lawannya adalah sedikit usaha lebih.", sumber: "Jesse Owens", kategori: "Sukses" },
  { teks: "Kesuksesan adalah guru yang buruk; ia menggoda orang cerdas mengira mereka tak bisa gagal.", sumber: "Bill Gates", kategori: "Pengusaha" },
  { teks: "Pelangganmu yang paling tidak puas adalah sumber belajarmu yang terbaik.", sumber: "Bill Gates", kategori: "Pengusaha" },
  { teks: "Bergeraklah cepat dan perbaiki hal-hal kecil sepanjang jalan.", sumber: "Anonim", kategori: "Pengusaha" },
  { teks: "Risiko terbesar adalah tidak mengambil risiko sama sekali.", sumber: "Mark Zuckerberg", kategori: "Pengusaha" },
  { teks: "Jika kau membangun sesuatu yang bermanfaat, uang akan menyusul.", sumber: "Anonim", kategori: "Pengusaha" },
  { teks: "Cara memulai adalah berhenti bicara dan mulai bekerja.", sumber: "Walt Disney", kategori: "Pengusaha" },
  { teks: "Semua impian bisa terwujud jika kita punya keberanian untuk mengejarnya.", sumber: "Walt Disney", kategori: "Pengusaha" },
  { teks: "Waktumu terbatas, jangan sia-siakan dengan menjalani hidup orang lain.", sumber: "Steve Jobs", kategori: "Pengusaha" },
  { teks: "Tetap lapar, tetap bodoh — teruslah haus belajar.", sumber: "Steve Jobs", kategori: "Pengusaha" },
  { teks: "Inovasi membedakan antara pemimpin dan pengikut.", sumber: "Steve Jobs", kategori: "Pengusaha" },
  { teks: "Kesabaran adalah kunci; telur tak menetas dengan dipukul, tapi dengan dierami.", sumber: "Arnold Glasow", kategori: "Sukses" },
  { teks: "Kesabaran itu pahit, tapi buahnya manis.", sumber: "Jean-Jacques Rousseau", kategori: "Sukses" },
  { teks: "Sebuah tujuan tanpa rencana hanyalah sebuah harapan.", sumber: "Antoine de Saint-Exupéry", kategori: "Sukses" },
  { teks: "Berikan aku enam jam menebang pohon, empat jam pertama akan kupakai mengasah kapak.", sumber: "Abraham Lincoln", kategori: "Sukses" },
  { teks: "Cara terbaik memprediksi masa depan adalah menciptakannya.", sumber: "Peter Drucker", kategori: "Sukses" },
  { teks: "Yang bisa diukur, bisa diperbaiki.", sumber: "Peter Drucker", kategori: "Sukses" },
  { teks: "Selesai lebih baik daripada sempurna.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Fokuslah pada langkah berikutnya, bukan pada seluruh tangga.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Melangkahlah walau kecil, asalkan tiap hari maju.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Jangan berhenti ketika lelah, berhentilah ketika selesai.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Kalau lelah, belajarlah beristirahat, bukan menyerah.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Selalu ada alasan untuk menyerah, tapi selalu ada satu alasan lebih kuat untuk bertahan.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Bekerja keraslah dalam diam, biarkan sukses yang bersuara.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Lebih baik lelah karena berbuat daripada lelah karena mengeluh.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Sukses bukan milik yang tercepat, tapi milik yang tak pernah berhenti.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Perbaiki caranya sedikit setiap hari, hasilnya akan melompat jauh.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Yang penting bukan seberapa banyak, tapi seberapa peduli.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Setiap ahli dulunya adalah pemula yang tidak menyerah.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Tangan yang bekerja lebih mulia daripada mulut yang menuntut.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Kerja keras tak pernah mengkhianati hasil.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Nikmati prosesnya, hasil akan mengikuti.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Jangan takut melangkah pelan, takutlah kalau hanya diam.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Semangat itu menular; mulailah dari dirimu.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Kalau bukan sekarang kapan lagi, kalau bukan kita siapa lagi.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Berikan lebih dari yang diminta, terimalah lebih dari yang diharapkan.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Ketekunan mengubah yang biasa menjadi luar biasa.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Jangan pernah meremehkan kekuatan konsistensi.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Air menetes lama-lama melubangi batu, bukan karena kuat tapi karena tekun.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Sehari selembar benang, lama-lama menjadi kain.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Sekali melangkah, pantang menyerah.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Hasil tidak akan mengkhianati usaha.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Tak kenal maka tak sayang, tak coba maka tak bisa.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Jadilah seperti padi: makin berisi makin merunduk.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Sepandai-pandai tupai melompat, akhirnya jatuh juga — teruslah rendah hati dan belajar.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Satu tangan tak bisa bertepuk; kebersamaan menguatkan.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Bagai aur dengan tebing — saling menopang, saling menguatkan.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Menanam kebaikan hari ini, memanen keberkahan esok hari.", sumber: "Peribahasa", kategori: "Peribahasa" },
  { teks: "Bekerja tanpa ilmu itu sia-sia, ilmu tanpa amal itu percuma.", sumber: "Pepatah", kategori: "Peribahasa" },
  { teks: "Kerja keras tanpa doa itu sombong, doa tanpa kerja keras itu kosong.", sumber: "Pepatah", kategori: "Peribahasa" },
  { teks: "Tanamkan kebiasaan baik, ia akan menuai nasib baik.", sumber: "Pepatah", kategori: "Peribahasa" },
  { teks: "Mulailah dengan Bismillah, akhiri dengan Alhamdulillah.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Barang siapa bersungguh-sungguh, ia akan mendapatkannya — man jadda wajada.", sumber: "Pepatah Arab", kategori: "Islami" },
  { teks: "Barang siapa bersabar, ia beruntung — man shabara zhafira.", sumber: "Pepatah Arab", kategori: "Islami" },
  { teks: "Sebaik-baik manusia adalah yang paling bermanfaat bagi sesamanya.", sumber: "HR. Ahmad", kategori: "Islami" },
  { teks: "Sesungguhnya bersama kesulitan ada kemudahan.", sumber: "QS. Al-Insyirah: 6", kategori: "Islami" },
  { teks: "Allah tidak membebani seseorang melainkan sesuai kesanggupannya.", sumber: "QS. Al-Baqarah: 286", kategori: "Islami" },
  { teks: "Bekerjalah, maka Allah, Rasul-Nya, dan orang beriman akan melihat pekerjaanmu.", sumber: "QS. At-Taubah: 105", kategori: "Islami" },
  { teks: "Bekerja itu ibadah, melayani itu berkah.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Berikan yang terbaik, sisanya biar Tuhan yang atur.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Sabar dan syukur adalah dua sayap menuju sukses.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Kerja keras adalah doa yang paling nyata.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Rezeki tidak akan tertukar; yang penting terus berikhtiar.", sumber: "Pepatah", kategori: "Islami" },
  { teks: "Ribuan piring hari ini bermula dari satu porsi yang kita siapkan sungguh-sungguh.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Melayani ribuan porsi bukan soal cepat, tapi soal ikhlas dan telaten.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Keringat kita hari ini adalah senyum anak-anak esok hari.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Kekompakan tim adalah bumbu utama setiap keberhasilan.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Masak dengan cinta, sajikan dengan bangga, layani dengan senyum.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Sekecil apa pun peranmu, kau bagian penting dari ribuan porsi hari ini.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Piring yang kita isi hari ini adalah gizi untuk generasi esok.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Dapur yang rapi adalah cerminan hati yang siap melayani.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Bahan yang cukup, takaran yang tepat, gizi yang terjaga.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Menghitung bahan dengan cermat adalah wujud tanggung jawab pada setiap porsi.", sumber: "Dapur MBG", kategori: "Dapur MBG" },
  { teks: "Sukses besar dibangun dari disiplin kecil yang dijaga setiap hari.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Semua yang besar berawal dari yang kecil yang dikerjakan sepenuh hati.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Kejarlah kualitas, jumlah akan mengikuti.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Setiap keringat yang jujur akan berbuah manis pada waktunya.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Yang membuat berbeda bukan kondisimu, tapi keputusanmu untuk terus melangkah.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Kesabaran dan kerja keras adalah kunci yang membuka semua pintu.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Awali dengan niat baik, jalani dengan usaha terbaik.", sumber: "Anonim", kategori: "Sukses" },
  { teks: "Bukan seberapa lambat kau berjalan, asalkan tidak berhenti.", sumber: "Konfusius", kategori: "Sukses" },
  { teks: "Perbuatan baik sekecil apa pun tidak pernah sia-sia.", sumber: "Aesop", kategori: "Sukses" },
  { teks: "Perjalanan seribu mil dimulai dari satu langkah.", sumber: "Lao Tzu", kategori: "Sukses" },
  { teks: "Ia yang bisa menaklukkan diri sendiri adalah pejuang terkuat.", sumber: "Konfusius", kategori: "Sukses" },
  { teks: "Bukan gunung yang kita taklukkan, melainkan diri kita sendiri.", sumber: "Edmund Hillary", kategori: "Sukses" },
  { teks: "Keberuntungan adalah pertemuan antara persiapan dan kesempatan.", sumber: "Seneca", kategori: "Sukses" },
  { teks: "Kesulitan mempersiapkan orang biasa untuk takdir yang luar biasa.", sumber: "C.S. Lewis", kategori: "Sukses" },
  { teks: "Jatuh tujuh kali, bangkit delapan kali.", sumber: "Pepatah Jepang", kategori: "Sukses" },
  { teks: "Sedikit lebih baik hari ini sudah cukup untuk membuat besok lebih cerah.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Kerja tim membuat mimpi besar bisa dipikul bersama.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Bekerja keras dalam kebersamaan meringankan yang terberat sekalipun.", sumber: "Anonim", kategori: "Semangat Kerja" },
  { teks: "Jangan biarkan kemarin memakan terlalu banyak hari ini.", sumber: "Will Rogers", kategori: "Sukses" },
  { teks: "Semakin keras kau bekerja, semakin beruntung kau terlihat.", sumber: "Gary Player", kategori: "Sukses" },
  { teks: "Impian tidak menjadi nyata lewat sihir; ia butuh keringat, tekad, dan kerja keras.", sumber: "Colin Powell", kategori: "Sukses" },
  { teks: "Berbuatlah baik tanpa perlu alasan, itulah tanda hati yang besar.", sumber: "Anonim", kategori: "Semangat Kerja" },
];
