ALTER TABLE production_plans
ADD COLUMN IF NOT EXISTS lateness_minutes BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS bottleneck_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0;

ALTER TABLE batch_checklist
ADD COLUMN IF NOT EXISTS scheduled_start TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS scheduled_end TIMESTAMPTZ;
